config/routes.rb
Rails.application.routes.draw do

  get 'index', to: 'home#index'
  get 'vendedores', to: 'home#vendedores'
  get 'detalhes/:service_number' => "home#detalhes", as: "detalhes"  
  get 'resultado' => "home#resultado", as: "resultado"
  get 'servico' => "home#busca_por_servico"  
  get 'estado' => "home#buscar_por_estado"
  devise_for :members
  
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
    before_action :authenticate_member!
    skip_before_action :verify_authenticity_token
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_action :authenticate_member!

  def index
    @dados_venda = Business.all
  end

  def vendedores
    @dados_vendedores = Business.select('distinct(seller_code), (seller_name)')
  end

  def detalhes
    @numero_servico = Business.where(service_number: params[:service_number])
    @buscar_numero_servico = @numero_servico.distinct.pluck(:service_number)
  end

  def busca_por_servico
    @buscar_por_servico = []

    @numero_servico = Business.where("service_number = ?", params[:service_number]).distinct.pluck(:service_number)

    @numero_servico.each do |num_serv|
      numero_servico = Business.where(service_number: num_serv).first
      numero_servico.amount = Business.where(service_number: num_serv).sum(:amount)

      @buscar_por_servico << numero_servico if numero_servico
    end
  end

  def buscar_por_estado
    @buscar_por_estado = []

    @estado = Business.where("business_situation = ?", params[:business_situation])
    @busca_estado_service_number = @estado.distinct.pluck(:service_number)

    @busca_estado_service_number.each do |serv_num|
      estado_negocio = Business.where(service_number: serv_num).first
      estado_negocio.amount = Business.where(service_number: serv_num).sum(:amount)

      @buscar_por_estado << estado_negocio if estado_negocio
    end
  end

  #Método trás soma das vendas que um vendedor fez
  def seller_amount(vendedor, buscar)
    buscar.where(seller_code: vendedor.seller_code).sum(:amount)
  end

  #Método trás a pocentagem que cada vendedor tem sobre o total de vendas
  def percent_of(vendas_vendedor, total_vendas)
    vendas_vendedor.to_f / total_vendas.to_f * 100.0
  end

  def resultado 
    
    @buscar_por_data = Business.where("date_service >= ? and date_service <= ?", params[:date_initial], params[:date_end])

    @buscar_numero_servico = @buscar_por_data.distinct.pluck(:service_number)
    @vendedores_code = @buscar_por_data.distinct.pluck(:seller_code)

    @busca_total_vendas_sem_orcamento = @buscar_por_data.where.not(payment_type: "Orçamento").sum(:amount)
    @busca_total_vendas_de_orcamento = @buscar_por_data.where("payment_type = 'Orçamento'").sum(:amount)
    
    @buscar_sem_orcamento = @buscar_por_data.where.not(payment_type: "Orçamento")
    @buscar_de_orcamento = @buscar_por_data.where("payment_type = 'Orçamento'")

    @vendas = []
    @vendedor_tipo_orcamento = []
    @vendedores = []

    @buscar_numero_servico.each do |num_serv|
      numero_servico = Business.where(service_number: num_serv).first
      numero_servico.amount = Business.where(service_number: num_serv).sum(:amount).round(2)

      @vendas << numero_servico if numero_servico
    end

    puts "--------------------------------------------------------------------------"
    puts @busca_total_vendas_de_orcamento
    @vendedores_code.each do |code|
      vendedor_tipo_faturamento = Business.where(seller_code: code).first
      vendedor_tipo_faturamento.amount = seller_amount(vendedor_tipo_faturamento, @buscar_sem_orcamento)
      vendedor_tipo_faturamento.product_value = percent_of(seller_amount(vendedor_tipo_faturamento, @buscar_sem_orcamento), @busca_total_vendas_sem_orcamento).round(2)

      

      @vendedores << vendedor_tipo_faturamento if vendedor_tipo_faturamento
      
    end
    @vendedores = @vendedores.sort {|a, b | b.amount <=> a.amount}

    @vendedores_code.each do |code|
      vendedor_tipo_orcamento = Business.where(seller_code: code).last
      vendedor_tipo_orcamento.amount = seller_amount(vendedor_tipo_orcamento, @buscar_de_orcamento)
      vendedor_tipo_orcamento.product_value = percent_of(seller_amount(vendedor_tipo_orcamento, @buscar_de_orcamento), @busca_total_vendas_de_orcamento).round(2)

      @vendedor_tipo_orcamento << vendedor_tipo_orcamento if vendedor_tipo_orcamento
    end
    @vendedor_tipo_orcamento = @vendedor_tipo_orcamento.sort {|a, b | b.amount <=> a.amount}

  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
    def seller_amount(vendedor, buscar)
        @buscar_por_data.where(seller_code: vendedor.seller_code).sum(:amount)
    end

    def percent_of(vendas_vendedor, total_vendas)
        vendas_vendedor.to_f / total_vendas.to_f * 100.0
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/busca_por_servico.html.erb
oi

app/views/home/buscar_por_estado.html.erb
<div class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title ">O que houve nesse período</h4>
                        <p class="card-category"> Informações de contatos comerciais</p>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-primary">
                                    <th>
                                        Número do Serviço
                                    </th>
                                    <th>
                                        Empresa
                                    </th>
                                    <th>
                                        Possível Entrada
                                    </th>
                                    <th>
                                        Vendedor
                                    </th>
                                    <th>
                                        Tipo de Pagamento
                                    </th>
                                    <th>
                                        Veja
                                    </th>
                                </thead>
                                <tbody>
                                    <% @buscar_por_estado.each do |estado|%>
                                        <tr>
                                            <td>
                                                <%= estado.service_number %>
                                            </td>
                                            <td>
                                                <%= estado.client_name %>
                                            </td>
                                            <td class="text-primary">
                                                R$<%= estado.amount %>
                                            </td>
                                            <td>
                                                <%= estado.seller_name %>
                                            </td>
                                            <td>
                                                <%= estado.payment_type %>
                                            </td>
                                            <td>
                                                <%= link_to detalhes_path(estado.service_number) do  %> 
                                                    <p>Detalhes</p>
                                                <%end%>
                                            </td>
                                        </tr>
                                    <%end%>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>        
    </div>
</div>

app/views/home/detalhes.html.erb
<div class="content">
    <div class="container-fluid">
        <!-- your content here -->
        <h3>Detalhes da transação comercial</h3>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title ">Serviço</h4>    
                            <p class="card-category">
                                <%=@buscar_numero_servico[0]%>     
                            </p>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-primary">
                                    <th>
                                        Descrição do Produto
                                    </th>
                                    <th>
                                        Valor Unitário
                                    </th>
                                    <th>
                                        Quantidade
                                    </th>
                                    <th>
                                        Desconto
                                    </th>
                                    <th>
                                        Situação do Negócio
                                    </th>
                                </thead>
                                <tbody>
                                    <% @numero_servico.each do |num_serv|%>
                                        <tr>
                                            <td>
                                                <%= num_serv.product_description %>
                                            </td>
                                            <td>
                                                <%= num_serv.product_value %>
                                            </td>
                                            <td>
                                                <%= num_serv.product_quantity %>
                                            </td>
                                            <td>
                                                <%= num_serv.product_discount %>
                                            </td>
                                            <td>
                                                <%= num_serv.business_situation %>
                                            </td>
                                        </tr>
                                    <%end%>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<div class="content">
    <div class="container-fluid">
        <!-- your content here -->
        <h3>Consultas de atendimento e faturamento</h3>
        <h4 id="calendar_title">Espaço temporal da consulta</h4>
            
        
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title ">O que houve nesse período</h4>
                        <p class="card-category"> Consulta por data</p>
                    </div>
                    <div class="card-content">
                        <%= form_with method: :get, url: resultado_path, local: true do |f| %>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group label-floating">
                                       <label for="dtp_input1" class="control-label">Data inicial</label>
                                        <div class="input-group date form_datetime" data-date-format="dd mm yyyy - hh:ii" data-link-field="dtp_input1">
                                            <%= f.date_field :date_initial, label: false, class: "form-control"%>
                                            <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                                            <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                                        </div>
                                        <input type="hidden" id="dtp_input1" value="" />
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group label-floating">
                                       <label for="dtp_input2" class="control-label">Data final</label>
                                        <div class="input-group date form_datetime" data-date-format="dd mm yyyy - hh:ii" data-link-field="dtp_input2">
                                            <%= f.date_field :date_end, label: false, class: "form-control"%>
                                            <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                                            <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                                        </div>
                                        <input type="hidden" id="dtp_input2" value="" />
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">INICIAR</button>
                            <div class="clearfix"></div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title ">O que houve nesse período</h4>
                        <p class="card-category"> Consulta por numero de serviço</p>
                    </div>
                    <div class="card-content">
                        <%= form_with method: :get, url: servico_path, local: true do |f| %>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group label-floating">
                                       <label for="dtp_input2" class="control-label">Numero do Serviço</label>
                                        
                                        <%= f.text_field :service_number, label: false, class: "form-control"%>
                                        <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                                        <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                                        
                                        <input type="hidden" id="dtp_input2" value="" />
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">INICIAR</button>
                            <div class="clearfix"></div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title ">O que houve nesse período</h4>
                        <p class="card-category"> Consulta por estado do negócio</p>
                    </div>
                    <div class="card-content">
                        <%= form_with method: :get, url: estado_path, local: true do |f| %>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group label-floating">
                                       <label for="dtp_input2" class="control-label">Estado do negócio: </label>
                                        <%=f.select(:business_situation, options_for_select([['Cancelada'],['Em Orçamento'], ['Nota Fical Emitida'], ['Cancelada'],['Emissão Liberada']]))%>
                                        <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                                        <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                        
                                        <input type="hidden" id="dtp_input2" value="" />

                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">INICIAR</button>
                            <div class="clearfix"></div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/resultado.html.erb
<div class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title ">O que houve nesse período</h4>
                        <p class="card-category"> Informações de contatos comerciais</p>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-primary">
                                    <th>
                                        Número do Serviço
                                    </th>
                                    <th>
                                        Empresa
                                    </th>
                                    <th>
                                        Possível Entrada
                                    </th>
                                    <th>
                                        Vendedor
                                    </th>
                                    <th>
                                        Tipo de Pagamento
                                    </th>
                                    <th>
                                        Veja
                                    </th>
                                </thead>
                                <tbody>
                                    <% @vendas.each do |venda|%>
                                        <tr>
                                            <td>
                                                <%= venda.service_number %>
                                            </td>
                                            <td>
                                                <%= venda.client_name %>
                                            </td>
                                            <td class="text-primary">
                                                R$<%= venda.amount %>
                                            </td>
                                            <td>
                                                <%= venda.seller_name %>
                                            </td>
                                            <td>
                                                <%= venda.payment_type %>
                                            </td>
                                            <td>
                                                <%= link_to detalhes_path(venda.service_number) do  %> 
                                                    <p>Detalhes</p>
                                                <%end%>
                                            </td>
                                        </tr>
                                    <%end%>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title ">Vendedores</h4>
                        <p class="card-category">Ranking de Faturamentos</p>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-primary">
                                    <th>
                                        ID
                                    </th>
                                    <th>
                                        Name
                                    </th>
                                    <th>
                                        Percentual do Total em (%)
                                    </th>
                                    <th>
                                        Faturamento Obtido em (R$)
                                    </th>
                                </thead>
                                <tbody>
                                    <%@vendedores.each do |vendedor|%>                                    
                                        <tr>
                                            <td>
                                                <%=vendedor.seller_code%>
                                            </td>
                                            <td>
                                                <%=vendedor.seller_name%>
                                            </td>
                                            <td>
                                                <%=vendedor.product_value%>
                                            </td>
                                            <td>
                                                <%=vendedor.amount%>
                                            </td>
                                        </tr>
                                    <%end%>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title ">Vendedores</h4>
                        <p class="card-category">Ranking de Orçamentos</p>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-primary">
                                    <th>
                                        ID
                                    </th>
                                    <th>
                                        Name
                                    </th>
                                    <th>
                                        Percentual do Total em (%)
                                    </th>
                                    <th>
                                        Orçamento Obtido em (R$)
                                    </th>
                                </thead>
                                <tbody>
                                    <%@vendedor_tipo_orcamento.each do |vendedor_orc|%>                                    
                                        <tr>
                                            <td>
                                                <%=vendedor_orc.seller_code%>
                                            </td>
                                            <td>
                                                <%=vendedor_orc.seller_name%>
                                            </td>
                                            <td>
                                                <%=vendedor_orc.product_value%>
                                            </td>
                                            <td>
                                                <%=vendedor_orc.amount%>
                                            </td>
                                        </tr>
                                    <%end%>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>        
    </div>
</div>

app/views/home/vendedores.html.erb
<div class="content">
    <div class="container-fluid">        
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title ">Vendedores</h4>
                    <p class="card-category"> Vendedores que você supervisiona</p>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                    <table class="table">
                        <thead class=" text-primary">
                        <th>
                            ID
                        </th>
                        <th>
                            Name
                        </th>
                        </thead>
                        <tbody>
                            <% @dados_vendedores.order(:seller_name).each do |informacoes_vendedores|%>
                                <tr>
                                    <td>
                                        <%= informacoes_vendedores.seller_code%>
                                    </td>
                                    <td>
                                        <%= informacoes_vendedores.seller_name%>
                                    </td>
                                </tr>
                            <%end%>
                        </tbody>
                    </table>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application' %>

    <link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>Sales Management</title>  

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">

  </head>
  <body class="">
    <div class="wrapper ">
      <div class="sidebar" data-color="purple" data-background-color="white" data-image="../assets/img/sidebar-1.jpg">
        <!--
          Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

          Tip 2: you can also add an image using data-image tag
        -->
        <div class="logo">
          <%= link_to "Sales Management", index_path, class: "simple-text logo-normal" %>
        </div>
        <div class="sidebar-wrapper">
          <ul class="nav">
            <li>
              <%= link_to index_path, class:"nav-link" do  %> 
                <i class="material-icons">dashboard</i>
                <p>Dashboard</p>
              <% end %>
            </li>
            <li>
              <%= link_to vendedores_path, class:"nav-link" do  %> 
                <i class="material-icons">person</i>
                <p>Vendedores</p>
              <%end%>
            </li>
          </ul>
        </div>
      </div>
      <div class="main-panel">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
          <div class="container-fluid">
            <div class="navbar-wrapper"></div>
            
            <div class="collapse navbar-collapse justify-content-end">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <%= link_to destroy_member_session_path, method: :delete, :class => "nav-link" do%>
                    Logout
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
        <div class="content">
          <div class="container-fluid">
            <%= yield %>
          </div>
        </div>
        <footer class="footer">
          <div class="container-fluid">
            <nav class="float-left">
              <ul>
                <li>
                  <a href="https://www.creative-tim.com">
                    Creative Tim
                  </a>
                </li>
                <li>
                  <a href="https://creative-tim.com/presentation">
                    About Us
                  </a>
                </li>
                <li>
                  <a href="http://blog.creative-tim.com">
                    Blog
                  </a>
                </li>
                <li>
                  <a href="https://www.creative-tim.com/license">
                    Licenses
                  </a>
                </li>
              </ul>
            </nav>
            <div class="copyright float-right">
              &copy;
              <script>
                document.write(new Date().getFullYear())
              </script>, made with <i class="material-icons">favorite</i> by
              <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a> for a better web.
            </div>
          </div>
        </footer>
      </div>
    </div>

    <%= javascript_include_tag 'application'%>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer">
    <div class="container-fluid">
        <div class="copyright float-right">
            &copy;
            System Development by Lucas de Amystherdam            
        </div>
    </div>
    Easter egg no footer!
</footer>